const shared = {
  typeValues: ["BUG", "FEATURE", "REFACTOR", "TEST", "INVESTIGATION", "DOCUMENTATION"],
  priorityValues: ["LOW", "NORMAL", "HIGH", "URGENT"],
};

const copies = {
  "pt-BR": {
    page: { back: "Voltar", eyebrow: "NOVA DEMANDA", title: "Descrever alteração", description: "Forneça contexto, resultado esperado e critérios verificáveis. A execução só inicia após aprovação de um Gestor." },
    project: "Projeto e repositório", projectPlaceholder: "Selecione o destino da demanda", type: "Tipo", priority: "Prioridade",
    types: { BUG: "Correção", FEATURE: "Nova funcionalidade", REFACTOR: "Refatoração", TEST: "Testes", INVESTIGATION: "Investigação", DOCUMENTATION: "Documentação de negócio" },
    priorities: { LOW: "Baixa", NORMAL: "Normal", HIGH: "Alta", URGENT: "Urgente" },
    viewExample: "Ver exemplo de {type}", exampleHelp: "Use este nível de detalhe para obter uma implementação mais precisa.",
    title: "Título", titleHelp: "Resuma a alteração e o local afetado.", context: "Contexto e resultado esperado", contextHelp: "Explique o comportamento atual, onde acontece e como deve funcionar depois.", acceptance: "Critérios de aceite", acceptanceHelp: "Liste condições objetivas que possam ser testadas ao final.",
    aiModel: "Modelo de IA", aiModelHelp: "Compare capacidade e custo relativo para um volume semelhante de tokens.", modelCost: "Custo de IA estimado: {multiplier}× Luna", modelCostSummary: "Terra ≈ 10× Luna · Sol ≈ 25× Luna e 2,5× Terra. O total real varia conforme o uso.", modelLocked: "Requer plano Studio ou superior.", freeModelNotice: "No plano gratuito, somente Luna está disponível.", viewPlans: "Ver planos",
    models: { "gpt-5.6-luna": ["Econômico", "Demandas simples, documentação e ajustes pequenos."], "gpt-5.6-terra": ["Equilibrado", "Recomendado para a maioria das implementações."], "gpt-5.6-sol": ["Avançado", "Mudanças complexas, críticas ou de grande alcance."] },
    visualValidation: "Exigir validação visual", visualValidationHelp: "Gera evidências em desktop e celular, sem substituir a aprovação do código.", visualPaths: "Rotas para validar (uma por linha)",
    noProjects: "Sem projetos disponíveis", noProjectsHelp: "Você precisa ser Gestor ou Desenvolvedor em pelo menos um projeto.", creating: "Criando...", submit: "Enviar para aprovação", createError: "Não foi possível criar a demanda",
    examples: {
      BUG: ["Corrigir perda dos dados ao voltar no cadastro", "No fluxo /cadastro, após preencher a etapa 2 e clicar em Voltar, os dados da etapa 1 são apagados. O usuário precisa preencher tudo novamente. Manter os valores já informados ao navegar entre as etapas, sem alterar as validações atuais.", "- Os campos preenchidos permanecem ao voltar e avançar.\n- A correção funciona em desktop e celular.\n- O envio final continua validando os campos obrigatórios."],
      FEATURE: ["Adicionar filtro por período no histórico de pedidos", "Na página /pedidos, permitir que o usuário filtre o histórico por data inicial e final. O filtro deve ser aplicado à listagem existente e permanecer na URL para poder ser compartilhado.", "- O período inicial não pode ser posterior ao final.\n- A listagem mostra apenas pedidos dentro do período.\n- Limpar filtros restaura a listagem completa.\n- O layout funciona em desktop e celular."],
      REFACTOR: ["Centralizar validação de permissões dos projetos", "As rotas de projetos repetem regras de acesso em pontos diferentes. Centralizar a validação no módulo de acesso existente, mantendo os mesmos papéis e respostas atuais da API.", "- Não alterar o comportamento das permissões existentes.\n- Remover a duplicação das regras nas rotas afetadas.\n- Manter ou adicionar testes para Gestor, Desenvolvedor e Visualizador."],
      TEST: ["Cobrir renovação e cancelamento de assinatura", "Adicionar testes automatizados para o ciclo de cobrança: confirmação do pagamento, renovação mensal, cancelamento e tentativa de processar novamente o mesmo webhook.", "- Cobrir os quatro cenários descritos.\n- Garantir idempotência do webhook.\n- A suíte completa deve continuar passando."],
      INVESTIGATION: ["Investigar lentidão ao carregar a página de projetos", "A página /projects leva entre 8 e 12 segundos para abrir quando a conta possui muitos repositórios. Identificar a origem com evidências e propor a correção mais segura, sem implementar mudanças antes da conclusão.", "- Apresentar a causa comprovada da lentidão.\n- Indicar consultas ou chamadas responsáveis pelo tempo.\n- Recomendar solução, riscos e forma de validação."],
      DOCUMENTATION: ["Documentar o fluxo de aprovação de pedidos", "Gerar documentação de negócio do fluxo de aprovação de pedidos a partir do código atual. Explicar atores, regras, estados, exceções e integrações em linguagem adequada para clientes e gestores.", "- Não expor segredos nem detalhes internos desnecessários.\n- Separar regras confirmadas de inferências.\n- Entregar DOCX e PDF com fluxo, regras e exceções."],
    },
  },
  en: {
    page: { back: "Back", eyebrow: "NEW REQUEST", title: "Describe the change", description: "Provide context, the expected result, and verifiable criteria. Execution only starts after a Manager approves it." },
    project: "Project and repository", projectPlaceholder: "Select the request destination", type: "Type", priority: "Priority",
    types: { BUG: "Bug fix", FEATURE: "New feature", REFACTOR: "Refactoring", TEST: "Tests", INVESTIGATION: "Investigation", DOCUMENTATION: "Business documentation" },
    priorities: { LOW: "Low", NORMAL: "Normal", HIGH: "High", URGENT: "Urgent" },
    viewExample: "View {type} example", exampleHelp: "Use this level of detail to obtain a more accurate implementation.",
    title: "Title", titleHelp: "Summarize the change and the affected area.", context: "Context and expected result", contextHelp: "Explain the current behavior, where it occurs, and how it should work afterward.", acceptance: "Acceptance criteria", acceptanceHelp: "List objective conditions that can be tested at the end.",
    aiModel: "AI model", aiModelHelp: "Compare capability and relative cost for a similar token volume.", modelCost: "Estimated AI cost: {multiplier}× Luna", modelCostSummary: "Terra ≈ 10× Luna · Sol ≈ 25× Luna and 2.5× Terra. Actual total varies with usage.", modelLocked: "Requires Studio plan or higher.", freeModelNotice: "Only Luna is available on the free plan.", viewPlans: "View plans",
    models: { "gpt-5.6-luna": ["Economy", "Simple requests, documentation, and small adjustments."], "gpt-5.6-terra": ["Balanced", "Recommended for most implementations."], "gpt-5.6-sol": ["Advanced", "Complex, critical, or broad changes."] },
    visualValidation: "Require visual validation", visualValidationHelp: "Produces desktop and mobile evidence without replacing code approval.", visualPaths: "Routes to validate (one per line)",
    noProjects: "No projects available", noProjectsHelp: "You must be a Manager or Developer in at least one project.", creating: "Creating...", submit: "Submit for approval", createError: "Could not create the request",
    examples: {
      BUG: ["Fix data loss when returning to the registration form", "In the /registration flow, after completing step 2 and selecting Back, the data from step 1 is cleared. The user has to enter everything again. Preserve entered values when navigating between steps without changing the current validations.", "- Completed fields remain filled when moving backward and forward.\n- The fix works on desktop and mobile.\n- Final submission still validates required fields."],
      FEATURE: ["Add a date range filter to order history", "On the /orders page, allow users to filter history by start and end date. Apply the filter to the current list and keep it in the URL so the result can be shared.", "- The start date cannot be after the end date.\n- The list only shows orders within the period.\n- Clearing filters restores the full list.\n- The layout works on desktop and mobile."],
      REFACTOR: ["Centralize project permission validation", "Project routes repeat access rules in several places. Centralize validation in the existing access module while preserving current roles and API responses.", "- Preserve existing permission behavior.\n- Remove duplicated rules from affected routes.\n- Keep or add tests for Manager, Developer, and Viewer."],
      TEST: ["Cover subscription renewal and cancellation", "Add automated tests for the billing lifecycle: payment confirmation, monthly renewal, cancellation, and an attempt to process the same webhook again.", "- Cover all four scenarios.\n- Guarantee webhook idempotency.\n- Keep the complete test suite passing."],
      INVESTIGATION: ["Investigate slow project page loading", "The /projects page takes 8 to 12 seconds to open when an account has many repositories. Identify the cause with evidence and propose the safest correction without implementing changes before the investigation is complete.", "- Present the proven cause of the delay.\n- Identify the responsible queries or calls.\n- Recommend a solution, risks, and validation method."],
      DOCUMENTATION: ["Document the order approval flow", "Generate business documentation for the order approval flow from the current code. Explain actors, rules, states, exceptions, and integrations in language suitable for clients and managers.", "- Do not expose secrets or unnecessary internal details.\n- Separate confirmed rules from inferences.\n- Deliver DOCX and PDF with the flow, rules, and exceptions."],
    },
  },
  es: {
    page: { back: "Volver", eyebrow: "NUEVA SOLICITUD", title: "Describir el cambio", description: "Proporciona contexto, resultado esperado y criterios verificables. La ejecución solo comienza después de la aprobación de un Gestor." },
    project: "Proyecto y repositorio", projectPlaceholder: "Selecciona el destino de la solicitud", type: "Tipo", priority: "Prioridad",
    types: { BUG: "Corrección", FEATURE: "Nueva funcionalidad", REFACTOR: "Refactorización", TEST: "Pruebas", INVESTIGATION: "Investigación", DOCUMENTATION: "Documentación de negocio" },
    priorities: { LOW: "Baja", NORMAL: "Normal", HIGH: "Alta", URGENT: "Urgente" },
    viewExample: "Ver ejemplo de {type}", exampleHelp: "Usa este nivel de detalle para obtener una implementación más precisa.",
    title: "Título", titleHelp: "Resume el cambio y el área afectada.", context: "Contexto y resultado esperado", contextHelp: "Explica el comportamiento actual, dónde ocurre y cómo debe funcionar después.", acceptance: "Criterios de aceptación", acceptanceHelp: "Enumera condiciones objetivas que puedan probarse al final.",
    aiModel: "Modelo de IA", aiModelHelp: "Compara capacidad y costo relativo para un volumen similar de tokens.", modelCost: "Costo estimado de IA: {multiplier}× Luna", modelCostSummary: "Terra ≈ 10× Luna · Sol ≈ 25× Luna y 2,5× Terra. El total real varía según el uso.", modelLocked: "Requiere el plan Studio o superior.", freeModelNotice: "En el plan gratuito solo está disponible Luna.", viewPlans: "Ver planes",
    models: { "gpt-5.6-luna": ["Económico", "Solicitudes simples, documentación y pequeños ajustes."], "gpt-5.6-terra": ["Equilibrado", "Recomendado para la mayoría de las implementaciones."], "gpt-5.6-sol": ["Avanzado", "Cambios complejos, críticos o de gran alcance."] },
    visualValidation: "Exigir validación visual", visualValidationHelp: "Genera evidencias en escritorio y móvil sin sustituir la aprobación del código.", visualPaths: "Rutas para validar (una por línea)",
    noProjects: "No hay proyectos disponibles", noProjectsHelp: "Debes ser Gestor o Desarrollador en al menos un proyecto.", creating: "Creando...", submit: "Enviar para aprobación", createError: "No se pudo crear la solicitud",
    examples: {
      BUG: ["Corregir la pérdida de datos al volver al registro", "En el flujo /registro, después de completar el paso 2 y seleccionar Volver, se borran los datos del paso 1. El usuario debe ingresar todo nuevamente. Conserva los valores al navegar entre pasos sin cambiar las validaciones actuales.", "- Los campos completados permanecen al avanzar y retroceder.\n- La corrección funciona en escritorio y móvil.\n- El envío final sigue validando los campos obligatorios."],
      FEATURE: ["Agregar filtro por período al historial de pedidos", "En la página /pedidos, permite filtrar el historial por fecha inicial y final. Aplica el filtro a la lista existente y mantenlo en la URL para que pueda compartirse.", "- La fecha inicial no puede ser posterior a la final.\n- La lista muestra solo pedidos del período.\n- Limpiar filtros restaura la lista completa.\n- El diseño funciona en escritorio y móvil."],
      REFACTOR: ["Centralizar la validación de permisos de proyectos", "Las rutas de proyectos repiten reglas de acceso en varios puntos. Centraliza la validación en el módulo de acceso existente, manteniendo los roles y respuestas actuales de la API.", "- Mantener el comportamiento de permisos existente.\n- Eliminar las reglas duplicadas de las rutas afectadas.\n- Mantener o agregar pruebas para Gestor, Desarrollador y Visualizador."],
      TEST: ["Cubrir la renovación y cancelación de suscripciones", "Agrega pruebas automatizadas para el ciclo de cobro: confirmación del pago, renovación mensual, cancelación e intento de procesar nuevamente el mismo webhook.", "- Cubrir los cuatro escenarios.\n- Garantizar la idempotencia del webhook.\n- Mantener toda la suite de pruebas aprobada."],
      INVESTIGATION: ["Investigar la lentitud al cargar la página de proyectos", "La página /projects tarda entre 8 y 12 segundos en abrir cuando la cuenta tiene muchos repositorios. Identifica la causa con evidencias y propone la corrección más segura sin implementar cambios antes de concluir la investigación.", "- Presentar la causa comprobada de la lentitud.\n- Identificar consultas o llamadas responsables.\n- Recomendar solución, riesgos y forma de validación."],
      DOCUMENTATION: ["Documentar el flujo de aprobación de pedidos", "Genera documentación de negocio del flujo de aprobación de pedidos a partir del código actual. Explica actores, reglas, estados, excepciones e integraciones con lenguaje adecuado para clientes y gestores.", "- No exponer secretos ni detalles internos innecesarios.\n- Separar reglas confirmadas de inferencias.\n- Entregar DOCX y PDF con flujo, reglas y excepciones."],
    },
  },
};

export function getDemandCopy(locale = "pt-BR") {
  return { ...shared, ...(copies[locale] ?? copies["pt-BR"]) };
}
