ALTER TYPE "DemandStatus" ADD VALUE IF NOT EXISTS 'STOPPED';
ALTER TYPE "ExecutionStatus" ADD VALUE IF NOT EXISTS 'STOPPED';

ALTER TABLE "Execution"
ADD COLUMN "stopRequestedAt" TIMESTAMP(3);

ALTER TABLE "GlobalSettings"
ADD COLUMN "executionProcessingEnabled" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "agentPowerMode" TEXT NOT NULL DEFAULT 'BALANCED',
ADD COLUMN "executionMaxAttempts" INTEGER NOT NULL DEFAULT 3,
ADD COLUMN "staleExecutionMinutes" INTEGER NOT NULL DEFAULT 30,
ADD COLUMN "healthCheckIntervalMinutes" INTEGER NOT NULL DEFAULT 5,
ADD COLUMN "healthCheckTimeoutSeconds" INTEGER NOT NULL DEFAULT 10,
ADD COLUMN "healthCheckConcurrency" INTEGER NOT NULL DEFAULT 10,
ADD COLUMN "healthCheckRetentionDays" INTEGER NOT NULL DEFAULT 30,
ADD COLUMN "previewPreparationTimeoutMinutes" INTEGER NOT NULL DEFAULT 15;
